### ISSUE TITLE
Can't find Province

### ISSUE THREAD

**Issue by ccp3638** [0xcaff/transloc-action#65]
I tried "Ask RIT Buses when the next bus arrives at Province" and "Ask RIT Buses when the next bus arrives at The Province" and every time the response is "Sorry I couldn't find a stop named 'Province'"

**Comment by 0xcaff** [comment]
Thanks for opening this issue! I can reproduce this and am trying to figure out a fix.

**Comment by 0xcaff** [comment]
This should be fixed. Deploying now.

**Comment by 0xcaff** [comment]
It has been deployed. Please re-open if you have any issues.

**Comment by 0xcaff** [comment]
You should be able to say:

> Ask rit buses when the next bus arrives at the province

to get information about buses arriving at the province.
